import Link from 'next/link'
import { ArrowRight, BookOpen, CalendarDays, CheckCircle2, Clock3, FileText, Mic2, ShieldCheck } from 'lucide-react'

const content: Record<string, { eyebrow: string; title: string; body: string; action: string; href: string; items: string[] }> = {
  apply: { eyebrow: 'Registration', title: 'Choose your examination.', body: 'Review available sessions and begin your application when you are ready.', action: 'Start application', href: '/apply/multilevel-2026/apply', items: ['Multilevel English Examination', 'Registration deadline shown by the backend', 'Secure application and billing flow'] },
  mock: { eyebrow: 'Practice', title: 'Prepare with a focused mock exam.', body: 'Get familiar with the examination format before your scheduled session.', action: 'Start mock exam', href: '/mock/multilevel-demo', items: ['Reading, listening, writing, speaking', 'Timed question experience', 'Review your performance afterwards'] },
  speaking: { eyebrow: 'Computer-based speaking', title: 'Your speaking session, clearly guided.', body: 'Review the requirements and understand each part before you enter the exam.', action: 'View speaking instructions', href: '/speaking/login', items: ['Microphone and browser check', 'Part 1.1, Part 1.2, Part 2, Part 3', 'Recorded responses submitted securely'] },
  result: { eyebrow: 'Results portal', title: 'Your result, when it is ready.', body: 'Track component assessment status and access documents published by the examination team.', action: 'Sign in to view result', href: '/dashboard', items: ['Component-by-component status', 'Final score when published', 'Download available documents'] },
  dashboard: { eyebrow: 'Candidate portal', title: 'Everything in one place.', body: 'Your application status, upcoming examination, speaking session, and result documents.', action: 'View application', href: '/apply', items: ['Application status: confirmed', 'Payment and schedule details', 'Result documents when available'] },
  admin: { eyebrow: 'Operations', title: 'Examination operations at a glance.', body: 'A role-aware workspace for managing applicants, sessions, assessments, billing, and results.', action: 'Review applications', href: '/admin/applications', items: ['Applicants and applications', 'Speaking assessments', 'Billing and result publication'] },
  about: { eyebrow: 'About the platform', title: 'A clear path through every exam step.', body: 'Multilevel.exam brings applications, practice, speaking sessions, and published results into one route-based platform.', action: 'Explore the examination', href: '/exams', items: ['One secure candidate portal', 'Clear application status', 'Documents when published'] },
  exams: { eyebrow: 'The examination', title: 'Understand the examination before you apply.', body: 'Review the components, application process, and candidate journey in one clear place.', action: 'View available exams', href: '/apply', items: ['Reading, listening, and writing', 'Computer-based speaking', 'Result status tracking'] },
  speakingLogin: { eyebrow: 'Speaking access', title: 'Enter your speaking session securely.', body: 'Use the access details provided by the examination service to continue to the pre-check.', action: 'Continue to pre-check', href: '/speaking/pre-check', items: ['Application number', 'Session access code', 'Microphone readiness check'] },
  verification: { eyebrow: 'Public verification', title: 'Verify a published examination result.', body: 'This page displays only the result information permitted by the backend verification response.', action: 'Return to results', href: '/result', items: ['Verification status', 'Candidate information', 'Published result details'] },
}

export default function SectionPage({ type }: { type: keyof typeof content }) { const data = content[type]; return <div className="min-h-screen"><header className="border-b bg-card"><div className="container-shell flex h-18 items-center justify-between"><Link href="/" className="font-semibold tracking-tight">Multilevel<span className="text-primary">.exam</span></Link><Link href="/" className="text-sm font-medium text-muted-foreground hover:text-foreground">Back to home</Link></div></header><main className="container-shell py-16 sm:py-24"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-wider text-primary">{data.eyebrow}</p><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-6xl">{data.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">{data.body}</p><Link href={data.href} className="mt-8 inline-flex rounded-lg bg-primary px-5 py-3.5 text-sm font-semibold text-primary-foreground">{data.action}<ArrowRight className="ml-2 size-4" /></Link></div><div className="mt-16 grid gap-4 md:grid-cols-3">{data.items.map((item, i) => <div className="surface p-6" key={item}><div className="flex size-10 items-center justify-center rounded-lg bg-secondary text-primary">{i === 0 ? <BookOpen className="size-5" /> : i === 1 ? <CalendarDays className="size-5" /> : <ShieldCheck className="size-5" />}</div><p className="mt-5 font-semibold">{item}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Designed to keep the next action clear.</p></div>)}</div></main></div> }
