'use client'
import Link from 'next/link'
import { useEffect,useState } from 'react'
import { ArrowLeft,ArrowRight,Clock3,Loader2,Mic2 } from 'lucide-react'
import { useParams,useRouter } from 'next/navigation'
import type { ReactNode } from 'react'
import { getPracticeTest,type SpeakingTest } from '@/lib/api/speaking'
import { saveSpeakingAccess } from '@/lib/speaking-session'
export default function Page(){const{id}=useParams<{id:string}>();const router=useRouter();const[test,setTest]=useState<SpeakingTest|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');useEffect(()=>{getPracticeTest(id).then(setTest).catch(e=>setError(e instanceof Error?e.message:'Test topilmadi.')).finally(()=>setLoading(false))},[id]);if(loading)return <main className="container-shell min-h-screen py-10"><Loader2 className="size-5 animate-spin"/></main>;if(error||!test)return <main className="container-shell min-h-screen py-10"><p className="text-sm text-red-600">{error||'Test topilmadi.'}</p><Link href="/speaking/tests" className="mt-4 inline-block text-sm font-semibold text-primary">← Testlar</Link></main>;return <main className="min-h-screen bg-muted/30"><header className="border-b bg-background"><div className="container-shell flex h-16 items-center"><Link href="/speaking/tests" className="text-sm text-muted-foreground"><ArrowLeft className="mr-2 inline size-4"/>Testlar</Link></div></header><section className="container-shell py-12"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Speaking test</p><h1 className="mt-3 text-4xl font-bold tracking-tight">{test.title}</h1><p className="mt-4 text-sm leading-7 text-muted-foreground">{test.description||'Multilevel Speaking formatidagi to‘liq practice testi.'}</p></div><div className="mt-8 grid gap-4 sm:grid-cols-3"><Info icon={<Mic2/>} title="4 blok" body="Part 1.1 / 1.2 / 2 / 3"/><Info icon={<Clock3/>} title="Timed" body="Tayyorgarlik va javob vaqti bilan"/><Info icon={<Mic2/>} title="Audio" body="Javoblar serverga yuboriladi"/></div><div className="mt-8 rounded-2xl border bg-background p-6"><h2 className="font-bold">Boshlashdan oldin</h2><ul className="mt-4 space-y-2 text-sm leading-6 text-muted-foreground"><li>• Mikrofon va quloqchinni tekshiring.</li><li>• Savolga javob berilgach, orqaga qaytib bo‘lmaydi.</li><li>• Vaqt tugaganda keyingi savol avtomatik ochiladi.</li><li>• Bu practice test — Mock natijasiga qo‘shilmaydi.</li></ul><button onClick={()=>{saveSpeakingAccess({mode:'practice',testId:test.id});router.push(`/speaking/exam?mode=practice&testId=${encodeURIComponent(test.id)}`)}} className="mt-6 inline-flex h-12 items-center gap-2 rounded-xl bg-primary px-6 text-sm font-bold text-primary-foreground">Testni boshlash <ArrowRight className="size-4"/></button></div></section></main>}
function Info({icon,title,body}:{icon:ReactNode,title:string,body:string}){return <div className="rounded-2xl border bg-background p-5"><div className="size-5 text-primary">{icon}</div><p className="mt-4 font-bold">{title}</p><p className="mt-1 text-sm text-muted-foreground">{body}</p></div>}
